server {
    listen 80;
    server_name localhost;

    root /home/jefferson/TF01/website;
    index index.html;

    access_log /var/log/nginx/sportmax_access.log;
    error_log /var/log/nginx/sportmax_error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
